CREATE TABLE IF NOT EXISTS "t3-app-latest_posts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-latest_posts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1)
);
--> statement-breakpoint
DROP TABLE "t3-app-latest_post";--> statement-breakpoint
ALTER TABLE "t3-app-latest_user" ADD CONSTRAINT "t3-app-latest_user_username_unique" UNIQUE("username");